"""add_tools_table

Revision ID: ffbe370a823f
Revises: 
Create Date: 2026-01-20 16:24:12.979659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ffbe370a823f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Unique tool identifier'),
    sa.Column('description', sa.Text(), nullable=False, comment='Human-readable tool description'),
    sa.Column('backend_url', sa.String(length=500), nullable=False, comment='URL to route requests to'),
    sa.Column('risk_level', sa.Enum('low', 'medium', 'high', name='risk_level_enum'), nullable=False, comment='Risk classification for policy checks'),
    sa.Column('required_roles', postgresql.ARRAY(sa.String(length=50)), nullable=True, comment='Optional role overrides for this tool'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether the tool is available'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Registration timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Last update timestamp'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tools_name'), 'tools', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tools_name'), table_name='tools')
    op.drop_table('tools')
    # ### end Alembic commands ###
